//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.01 at 10:09:16 PM IST 
//


package org.openmrs.module.dhisintegration.api.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for CategoryCombosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryCombosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categoryOptionCombo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="categoryCombo">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="categoryOptions">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="categoryOption" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryCombosType", propOrder = {
    "categoryOptionCombo"
})
public class CategoryCombosType
    implements Cloneable, CopyTo, Equals, HashCode, ToString
{

    protected List<CategoryCombosType.CategoryOptionCombo> categoryOptionCombo;

    /**
     * Gets the value of the categoryOptionCombo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryOptionCombo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryOptionCombo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryCombosType.CategoryOptionCombo }
     * 
     * 
     */
    public List<CategoryCombosType.CategoryOptionCombo> getCategoryOptionCombo() {
        if (categoryOptionCombo == null) {
            categoryOptionCombo = new ArrayList<CategoryCombosType.CategoryOptionCombo>();
        }
        return this.categoryOptionCombo;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<CategoryCombosType.CategoryOptionCombo> theCategoryOptionCombo;
            theCategoryOptionCombo = (((this.categoryOptionCombo!= null)&&(!this.categoryOptionCombo.isEmpty()))?this.getCategoryOptionCombo():null);
            strategy.appendField(locator, this, "categoryOptionCombo", buffer, theCategoryOptionCombo);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CategoryCombosType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CategoryCombosType that = ((CategoryCombosType) object);
        {
            List<CategoryCombosType.CategoryOptionCombo> lhsCategoryOptionCombo;
            lhsCategoryOptionCombo = (((this.categoryOptionCombo!= null)&&(!this.categoryOptionCombo.isEmpty()))?this.getCategoryOptionCombo():null);
            List<CategoryCombosType.CategoryOptionCombo> rhsCategoryOptionCombo;
            rhsCategoryOptionCombo = (((that.categoryOptionCombo!= null)&&(!that.categoryOptionCombo.isEmpty()))?that.getCategoryOptionCombo():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "categoryOptionCombo", lhsCategoryOptionCombo), LocatorUtils.property(thatLocator, "categoryOptionCombo", rhsCategoryOptionCombo), lhsCategoryOptionCombo, rhsCategoryOptionCombo)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<CategoryCombosType.CategoryOptionCombo> theCategoryOptionCombo;
            theCategoryOptionCombo = (((this.categoryOptionCombo!= null)&&(!this.categoryOptionCombo.isEmpty()))?this.getCategoryOptionCombo():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "categoryOptionCombo", theCategoryOptionCombo), currentHashCode, theCategoryOptionCombo);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof CategoryCombosType) {
            final CategoryCombosType copy = ((CategoryCombosType) draftCopy);
            if ((this.categoryOptionCombo!= null)&&(!this.categoryOptionCombo.isEmpty())) {
                List<CategoryCombosType.CategoryOptionCombo> sourceCategoryOptionCombo;
                sourceCategoryOptionCombo = (((this.categoryOptionCombo!= null)&&(!this.categoryOptionCombo.isEmpty()))?this.getCategoryOptionCombo():null);
                @SuppressWarnings("unchecked")
                List<CategoryCombosType.CategoryOptionCombo> copyCategoryOptionCombo = ((List<CategoryCombosType.CategoryOptionCombo> ) strategy.copy(LocatorUtils.property(locator, "categoryOptionCombo", sourceCategoryOptionCombo), sourceCategoryOptionCombo));
                copy.categoryOptionCombo = null;
                if (copyCategoryOptionCombo!= null) {
                    List<CategoryCombosType.CategoryOptionCombo> uniqueCategoryOptionCombol = copy.getCategoryOptionCombo();
                    uniqueCategoryOptionCombol.addAll(copyCategoryOptionCombo);
                }
            } else {
                copy.categoryOptionCombo = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new CategoryCombosType();
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="categoryCombo">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="categoryOptions">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="categoryOption" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "categoryCombo",
        "categoryOptions"
    })
    public static class CategoryOptionCombo
        implements Cloneable, CopyTo, Equals, HashCode, ToString
    {

        @XmlElement(required = true)
        protected CategoryCombosType.CategoryOptionCombo.CategoryCombo categoryCombo;
        @XmlElement(required = true)
        protected CategoryCombosType.CategoryOptionCombo.CategoryOptions categoryOptions;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "created")
        protected String created;
        @XmlAttribute(name = "lastUpdated")
        protected String lastUpdated;
        @XmlAttribute(name = "href")
        @XmlSchemaType(name = "anyURI")
        protected String href;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the categoryCombo property.
         * 
         * @return
         *     possible object is
         *     {@link CategoryCombosType.CategoryOptionCombo.CategoryCombo }
         *     
         */
        public CategoryCombosType.CategoryOptionCombo.CategoryCombo getCategoryCombo() {
            return categoryCombo;
        }

        /**
         * Sets the value of the categoryCombo property.
         * 
         * @param value
         *     allowed object is
         *     {@link CategoryCombosType.CategoryOptionCombo.CategoryCombo }
         *     
         */
        public void setCategoryCombo(CategoryCombosType.CategoryOptionCombo.CategoryCombo value) {
            this.categoryCombo = value;
        }

        /**
         * Gets the value of the categoryOptions property.
         * 
         * @return
         *     possible object is
         *     {@link CategoryCombosType.CategoryOptionCombo.CategoryOptions }
         *     
         */
        public CategoryCombosType.CategoryOptionCombo.CategoryOptions getCategoryOptions() {
            return categoryOptions;
        }

        /**
         * Sets the value of the categoryOptions property.
         * 
         * @param value
         *     allowed object is
         *     {@link CategoryCombosType.CategoryOptionCombo.CategoryOptions }
         *     
         */
        public void setCategoryOptions(CategoryCombosType.CategoryOptionCombo.CategoryOptions value) {
            this.categoryOptions = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the created property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreated() {
            return created;
        }

        /**
         * Sets the value of the created property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreated(String value) {
            this.created = value;
        }

        /**
         * Gets the value of the lastUpdated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastUpdated() {
            return lastUpdated;
        }

        /**
         * Sets the value of the lastUpdated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastUpdated(String value) {
            this.lastUpdated = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            {
                CategoryCombosType.CategoryOptionCombo.CategoryCombo theCategoryCombo;
                theCategoryCombo = this.getCategoryCombo();
                strategy.appendField(locator, this, "categoryCombo", buffer, theCategoryCombo);
            }
            {
                CategoryCombosType.CategoryOptionCombo.CategoryOptions theCategoryOptions;
                theCategoryOptions = this.getCategoryOptions();
                strategy.appendField(locator, this, "categoryOptions", buffer, theCategoryOptions);
            }
            {
                String theName;
                theName = this.getName();
                strategy.appendField(locator, this, "name", buffer, theName);
            }
            {
                String theCreated;
                theCreated = this.getCreated();
                strategy.appendField(locator, this, "created", buffer, theCreated);
            }
            {
                String theLastUpdated;
                theLastUpdated = this.getLastUpdated();
                strategy.appendField(locator, this, "lastUpdated", buffer, theLastUpdated);
            }
            {
                String theHref;
                theHref = this.getHref();
                strategy.appendField(locator, this, "href", buffer, theHref);
            }
            {
                String theId;
                theId = this.getId();
                strategy.appendField(locator, this, "id", buffer, theId);
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof CategoryCombosType.CategoryOptionCombo)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final CategoryCombosType.CategoryOptionCombo that = ((CategoryCombosType.CategoryOptionCombo) object);
            {
                CategoryCombosType.CategoryOptionCombo.CategoryCombo lhsCategoryCombo;
                lhsCategoryCombo = this.getCategoryCombo();
                CategoryCombosType.CategoryOptionCombo.CategoryCombo rhsCategoryCombo;
                rhsCategoryCombo = that.getCategoryCombo();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "categoryCombo", lhsCategoryCombo), LocatorUtils.property(thatLocator, "categoryCombo", rhsCategoryCombo), lhsCategoryCombo, rhsCategoryCombo)) {
                    return false;
                }
            }
            {
                CategoryCombosType.CategoryOptionCombo.CategoryOptions lhsCategoryOptions;
                lhsCategoryOptions = this.getCategoryOptions();
                CategoryCombosType.CategoryOptionCombo.CategoryOptions rhsCategoryOptions;
                rhsCategoryOptions = that.getCategoryOptions();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "categoryOptions", lhsCategoryOptions), LocatorUtils.property(thatLocator, "categoryOptions", rhsCategoryOptions), lhsCategoryOptions, rhsCategoryOptions)) {
                    return false;
                }
            }
            {
                String lhsName;
                lhsName = this.getName();
                String rhsName;
                rhsName = that.getName();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "name", lhsName), LocatorUtils.property(thatLocator, "name", rhsName), lhsName, rhsName)) {
                    return false;
                }
            }
            {
                String lhsCreated;
                lhsCreated = this.getCreated();
                String rhsCreated;
                rhsCreated = that.getCreated();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "created", lhsCreated), LocatorUtils.property(thatLocator, "created", rhsCreated), lhsCreated, rhsCreated)) {
                    return false;
                }
            }
            {
                String lhsLastUpdated;
                lhsLastUpdated = this.getLastUpdated();
                String rhsLastUpdated;
                rhsLastUpdated = that.getLastUpdated();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "lastUpdated", lhsLastUpdated), LocatorUtils.property(thatLocator, "lastUpdated", rhsLastUpdated), lhsLastUpdated, rhsLastUpdated)) {
                    return false;
                }
            }
            {
                String lhsHref;
                lhsHref = this.getHref();
                String rhsHref;
                rhsHref = that.getHref();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "href", lhsHref), LocatorUtils.property(thatLocator, "href", rhsHref), lhsHref, rhsHref)) {
                    return false;
                }
            }
            {
                String lhsId;
                lhsId = this.getId();
                String rhsId;
                rhsId = that.getId();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsId), LocatorUtils.property(thatLocator, "id", rhsId), lhsId, rhsId)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                CategoryCombosType.CategoryOptionCombo.CategoryCombo theCategoryCombo;
                theCategoryCombo = this.getCategoryCombo();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "categoryCombo", theCategoryCombo), currentHashCode, theCategoryCombo);
            }
            {
                CategoryCombosType.CategoryOptionCombo.CategoryOptions theCategoryOptions;
                theCategoryOptions = this.getCategoryOptions();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "categoryOptions", theCategoryOptions), currentHashCode, theCategoryOptions);
            }
            {
                String theName;
                theName = this.getName();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "name", theName), currentHashCode, theName);
            }
            {
                String theCreated;
                theCreated = this.getCreated();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "created", theCreated), currentHashCode, theCreated);
            }
            {
                String theLastUpdated;
                theLastUpdated = this.getLastUpdated();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lastUpdated", theLastUpdated), currentHashCode, theLastUpdated);
            }
            {
                String theHref;
                theHref = this.getHref();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "href", theHref), currentHashCode, theHref);
            }
            {
                String theId;
                theId = this.getId();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theId), currentHashCode, theId);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof CategoryCombosType.CategoryOptionCombo) {
                final CategoryCombosType.CategoryOptionCombo copy = ((CategoryCombosType.CategoryOptionCombo) draftCopy);
                if (this.categoryCombo!= null) {
                    CategoryCombosType.CategoryOptionCombo.CategoryCombo sourceCategoryCombo;
                    sourceCategoryCombo = this.getCategoryCombo();
                    CategoryCombosType.CategoryOptionCombo.CategoryCombo copyCategoryCombo = ((CategoryCombosType.CategoryOptionCombo.CategoryCombo) strategy.copy(LocatorUtils.property(locator, "categoryCombo", sourceCategoryCombo), sourceCategoryCombo));
                    copy.setCategoryCombo(copyCategoryCombo);
                } else {
                    copy.categoryCombo = null;
                }
                if (this.categoryOptions!= null) {
                    CategoryCombosType.CategoryOptionCombo.CategoryOptions sourceCategoryOptions;
                    sourceCategoryOptions = this.getCategoryOptions();
                    CategoryCombosType.CategoryOptionCombo.CategoryOptions copyCategoryOptions = ((CategoryCombosType.CategoryOptionCombo.CategoryOptions) strategy.copy(LocatorUtils.property(locator, "categoryOptions", sourceCategoryOptions), sourceCategoryOptions));
                    copy.setCategoryOptions(copyCategoryOptions);
                } else {
                    copy.categoryOptions = null;
                }
                if (this.name!= null) {
                    String sourceName;
                    sourceName = this.getName();
                    String copyName = ((String) strategy.copy(LocatorUtils.property(locator, "name", sourceName), sourceName));
                    copy.setName(copyName);
                } else {
                    copy.name = null;
                }
                if (this.created!= null) {
                    String sourceCreated;
                    sourceCreated = this.getCreated();
                    String copyCreated = ((String) strategy.copy(LocatorUtils.property(locator, "created", sourceCreated), sourceCreated));
                    copy.setCreated(copyCreated);
                } else {
                    copy.created = null;
                }
                if (this.lastUpdated!= null) {
                    String sourceLastUpdated;
                    sourceLastUpdated = this.getLastUpdated();
                    String copyLastUpdated = ((String) strategy.copy(LocatorUtils.property(locator, "lastUpdated", sourceLastUpdated), sourceLastUpdated));
                    copy.setLastUpdated(copyLastUpdated);
                } else {
                    copy.lastUpdated = null;
                }
                if (this.href!= null) {
                    String sourceHref;
                    sourceHref = this.getHref();
                    String copyHref = ((String) strategy.copy(LocatorUtils.property(locator, "href", sourceHref), sourceHref));
                    copy.setHref(copyHref);
                } else {
                    copy.href = null;
                }
                if (this.id!= null) {
                    String sourceId;
                    sourceId = this.getId();
                    String copyId = ((String) strategy.copy(LocatorUtils.property(locator, "id", sourceId), sourceId));
                    copy.setId(copyId);
                } else {
                    copy.id = null;
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new CategoryCombosType.CategoryOptionCombo();
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CategoryCombo
            implements Cloneable, CopyTo, Equals, HashCode, ToString
        {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "created")
            protected String created;
            @XmlAttribute(name = "lastUpdated")
            protected String lastUpdated;
            @XmlAttribute(name = "href")
            @XmlSchemaType(name = "anyURI")
            protected String href;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the created property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCreated() {
                return created;
            }

            /**
             * Sets the value of the created property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCreated(String value) {
                this.created = value;
            }

            /**
             * Gets the value of the lastUpdated property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLastUpdated() {
                return lastUpdated;
            }

            /**
             * Sets the value of the lastUpdated property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLastUpdated(String value) {
                this.lastUpdated = value;
            }

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            public String toString() {
                final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
                final StringBuilder buffer = new StringBuilder();
                append(null, buffer, strategy);
                return buffer.toString();
            }

            public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                strategy.appendStart(locator, this, buffer);
                appendFields(locator, buffer, strategy);
                strategy.appendEnd(locator, this, buffer);
                return buffer;
            }

            public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                {
                    String theValue;
                    theValue = this.getValue();
                    strategy.appendField(locator, this, "value", buffer, theValue);
                }
                {
                    String theName;
                    theName = this.getName();
                    strategy.appendField(locator, this, "name", buffer, theName);
                }
                {
                    String theCreated;
                    theCreated = this.getCreated();
                    strategy.appendField(locator, this, "created", buffer, theCreated);
                }
                {
                    String theLastUpdated;
                    theLastUpdated = this.getLastUpdated();
                    strategy.appendField(locator, this, "lastUpdated", buffer, theLastUpdated);
                }
                {
                    String theHref;
                    theHref = this.getHref();
                    strategy.appendField(locator, this, "href", buffer, theHref);
                }
                {
                    String theId;
                    theId = this.getId();
                    strategy.appendField(locator, this, "id", buffer, theId);
                }
                return buffer;
            }

            public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                if (!(object instanceof CategoryCombosType.CategoryOptionCombo.CategoryCombo)) {
                    return false;
                }
                if (this == object) {
                    return true;
                }
                final CategoryCombosType.CategoryOptionCombo.CategoryCombo that = ((CategoryCombosType.CategoryOptionCombo.CategoryCombo) object);
                {
                    String lhsValue;
                    lhsValue = this.getValue();
                    String rhsValue;
                    rhsValue = that.getValue();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue), LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue)) {
                        return false;
                    }
                }
                {
                    String lhsName;
                    lhsName = this.getName();
                    String rhsName;
                    rhsName = that.getName();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "name", lhsName), LocatorUtils.property(thatLocator, "name", rhsName), lhsName, rhsName)) {
                        return false;
                    }
                }
                {
                    String lhsCreated;
                    lhsCreated = this.getCreated();
                    String rhsCreated;
                    rhsCreated = that.getCreated();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "created", lhsCreated), LocatorUtils.property(thatLocator, "created", rhsCreated), lhsCreated, rhsCreated)) {
                        return false;
                    }
                }
                {
                    String lhsLastUpdated;
                    lhsLastUpdated = this.getLastUpdated();
                    String rhsLastUpdated;
                    rhsLastUpdated = that.getLastUpdated();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "lastUpdated", lhsLastUpdated), LocatorUtils.property(thatLocator, "lastUpdated", rhsLastUpdated), lhsLastUpdated, rhsLastUpdated)) {
                        return false;
                    }
                }
                {
                    String lhsHref;
                    lhsHref = this.getHref();
                    String rhsHref;
                    rhsHref = that.getHref();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "href", lhsHref), LocatorUtils.property(thatLocator, "href", rhsHref), lhsHref, rhsHref)) {
                        return false;
                    }
                }
                {
                    String lhsId;
                    lhsId = this.getId();
                    String rhsId;
                    rhsId = that.getId();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsId), LocatorUtils.property(thatLocator, "id", rhsId), lhsId, rhsId)) {
                        return false;
                    }
                }
                return true;
            }

            public boolean equals(Object object) {
                final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                return equals(null, null, object, strategy);
            }

            public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                int currentHashCode = 1;
                {
                    String theValue;
                    theValue = this.getValue();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue);
                }
                {
                    String theName;
                    theName = this.getName();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "name", theName), currentHashCode, theName);
                }
                {
                    String theCreated;
                    theCreated = this.getCreated();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "created", theCreated), currentHashCode, theCreated);
                }
                {
                    String theLastUpdated;
                    theLastUpdated = this.getLastUpdated();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lastUpdated", theLastUpdated), currentHashCode, theLastUpdated);
                }
                {
                    String theHref;
                    theHref = this.getHref();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "href", theHref), currentHashCode, theHref);
                }
                {
                    String theId;
                    theId = this.getId();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theId), currentHashCode, theId);
                }
                return currentHashCode;
            }

            public int hashCode() {
                final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                return this.hashCode(null, strategy);
            }

            public Object clone() {
                return copyTo(createNewInstance());
            }

            public Object copyTo(Object target) {
                final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
                return copyTo(null, target, strategy);
            }

            public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
                final Object draftCopy = ((target == null)?createNewInstance():target);
                if (draftCopy instanceof CategoryCombosType.CategoryOptionCombo.CategoryCombo) {
                    final CategoryCombosType.CategoryOptionCombo.CategoryCombo copy = ((CategoryCombosType.CategoryOptionCombo.CategoryCombo) draftCopy);
                    if (this.value!= null) {
                        String sourceValue;
                        sourceValue = this.getValue();
                        String copyValue = ((String) strategy.copy(LocatorUtils.property(locator, "value", sourceValue), sourceValue));
                        copy.setValue(copyValue);
                    } else {
                        copy.value = null;
                    }
                    if (this.name!= null) {
                        String sourceName;
                        sourceName = this.getName();
                        String copyName = ((String) strategy.copy(LocatorUtils.property(locator, "name", sourceName), sourceName));
                        copy.setName(copyName);
                    } else {
                        copy.name = null;
                    }
                    if (this.created!= null) {
                        String sourceCreated;
                        sourceCreated = this.getCreated();
                        String copyCreated = ((String) strategy.copy(LocatorUtils.property(locator, "created", sourceCreated), sourceCreated));
                        copy.setCreated(copyCreated);
                    } else {
                        copy.created = null;
                    }
                    if (this.lastUpdated!= null) {
                        String sourceLastUpdated;
                        sourceLastUpdated = this.getLastUpdated();
                        String copyLastUpdated = ((String) strategy.copy(LocatorUtils.property(locator, "lastUpdated", sourceLastUpdated), sourceLastUpdated));
                        copy.setLastUpdated(copyLastUpdated);
                    } else {
                        copy.lastUpdated = null;
                    }
                    if (this.href!= null) {
                        String sourceHref;
                        sourceHref = this.getHref();
                        String copyHref = ((String) strategy.copy(LocatorUtils.property(locator, "href", sourceHref), sourceHref));
                        copy.setHref(copyHref);
                    } else {
                        copy.href = null;
                    }
                    if (this.id!= null) {
                        String sourceId;
                        sourceId = this.getId();
                        String copyId = ((String) strategy.copy(LocatorUtils.property(locator, "id", sourceId), sourceId));
                        copy.setId(copyId);
                    } else {
                        copy.id = null;
                    }
                }
                return draftCopy;
            }

            public Object createNewInstance() {
                return new CategoryCombosType.CategoryOptionCombo.CategoryCombo();
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="categoryOption" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "categoryOption"
        })
        public static class CategoryOptions
            implements Cloneable, CopyTo, Equals, HashCode, ToString
        {

            protected List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> categoryOption;

            /**
             * Gets the value of the categoryOption property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the categoryOption property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCategoryOption().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption }
             * 
             * 
             */
            public List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> getCategoryOption() {
                if (categoryOption == null) {
                    categoryOption = new ArrayList<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption>();
                }
                return this.categoryOption;
            }

            public String toString() {
                final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
                final StringBuilder buffer = new StringBuilder();
                append(null, buffer, strategy);
                return buffer.toString();
            }

            public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                strategy.appendStart(locator, this, buffer);
                appendFields(locator, buffer, strategy);
                strategy.appendEnd(locator, this, buffer);
                return buffer;
            }

            public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                {
                    List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> theCategoryOption;
                    theCategoryOption = (((this.categoryOption!= null)&&(!this.categoryOption.isEmpty()))?this.getCategoryOption():null);
                    strategy.appendField(locator, this, "categoryOption", buffer, theCategoryOption);
                }
                return buffer;
            }

            public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                if (!(object instanceof CategoryCombosType.CategoryOptionCombo.CategoryOptions)) {
                    return false;
                }
                if (this == object) {
                    return true;
                }
                final CategoryCombosType.CategoryOptionCombo.CategoryOptions that = ((CategoryCombosType.CategoryOptionCombo.CategoryOptions) object);
                {
                    List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> lhsCategoryOption;
                    lhsCategoryOption = (((this.categoryOption!= null)&&(!this.categoryOption.isEmpty()))?this.getCategoryOption():null);
                    List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> rhsCategoryOption;
                    rhsCategoryOption = (((that.categoryOption!= null)&&(!that.categoryOption.isEmpty()))?that.getCategoryOption():null);
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "categoryOption", lhsCategoryOption), LocatorUtils.property(thatLocator, "categoryOption", rhsCategoryOption), lhsCategoryOption, rhsCategoryOption)) {
                        return false;
                    }
                }
                return true;
            }

            public boolean equals(Object object) {
                final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                return equals(null, null, object, strategy);
            }

            public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                int currentHashCode = 1;
                {
                    List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> theCategoryOption;
                    theCategoryOption = (((this.categoryOption!= null)&&(!this.categoryOption.isEmpty()))?this.getCategoryOption():null);
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "categoryOption", theCategoryOption), currentHashCode, theCategoryOption);
                }
                return currentHashCode;
            }

            public int hashCode() {
                final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                return this.hashCode(null, strategy);
            }

            public Object clone() {
                return copyTo(createNewInstance());
            }

            public Object copyTo(Object target) {
                final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
                return copyTo(null, target, strategy);
            }

            public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
                final Object draftCopy = ((target == null)?createNewInstance():target);
                if (draftCopy instanceof CategoryCombosType.CategoryOptionCombo.CategoryOptions) {
                    final CategoryCombosType.CategoryOptionCombo.CategoryOptions copy = ((CategoryCombosType.CategoryOptionCombo.CategoryOptions) draftCopy);
                    if ((this.categoryOption!= null)&&(!this.categoryOption.isEmpty())) {
                        List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> sourceCategoryOption;
                        sourceCategoryOption = (((this.categoryOption!= null)&&(!this.categoryOption.isEmpty()))?this.getCategoryOption():null);
                        @SuppressWarnings("unchecked")
                        List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> copyCategoryOption = ((List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> ) strategy.copy(LocatorUtils.property(locator, "categoryOption", sourceCategoryOption), sourceCategoryOption));
                        copy.categoryOption = null;
                        if (copyCategoryOption!= null) {
                            List<CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption> uniqueCategoryOptionl = copy.getCategoryOption();
                            uniqueCategoryOptionl.addAll(copyCategoryOption);
                        }
                    } else {
                        copy.categoryOption = null;
                    }
                }
                return draftCopy;
            }

            public Object createNewInstance() {
                return new CategoryCombosType.CategoryOptionCombo.CategoryOptions();
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class CategoryOption
                implements Cloneable, CopyTo, Equals, HashCode, ToString
            {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "created")
                protected String created;
                @XmlAttribute(name = "lastUpdated")
                protected String lastUpdated;
                @XmlAttribute(name = "href")
                @XmlSchemaType(name = "anyURI")
                protected String href;
                @XmlAttribute(name = "id")
                protected String id;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the created property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCreated() {
                    return created;
                }

                /**
                 * Sets the value of the created property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCreated(String value) {
                    this.created = value;
                }

                /**
                 * Gets the value of the lastUpdated property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLastUpdated() {
                    return lastUpdated;
                }

                /**
                 * Sets the value of the lastUpdated property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLastUpdated(String value) {
                    this.lastUpdated = value;
                }

                /**
                 * Gets the value of the href property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHref() {
                    return href;
                }

                /**
                 * Sets the value of the href property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHref(String value) {
                    this.href = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                public String toString() {
                    final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
                    final StringBuilder buffer = new StringBuilder();
                    append(null, buffer, strategy);
                    return buffer.toString();
                }

                public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                    strategy.appendStart(locator, this, buffer);
                    appendFields(locator, buffer, strategy);
                    strategy.appendEnd(locator, this, buffer);
                    return buffer;
                }

                public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                    {
                        String theValue;
                        theValue = this.getValue();
                        strategy.appendField(locator, this, "value", buffer, theValue);
                    }
                    {
                        String theName;
                        theName = this.getName();
                        strategy.appendField(locator, this, "name", buffer, theName);
                    }
                    {
                        String theCreated;
                        theCreated = this.getCreated();
                        strategy.appendField(locator, this, "created", buffer, theCreated);
                    }
                    {
                        String theLastUpdated;
                        theLastUpdated = this.getLastUpdated();
                        strategy.appendField(locator, this, "lastUpdated", buffer, theLastUpdated);
                    }
                    {
                        String theHref;
                        theHref = this.getHref();
                        strategy.appendField(locator, this, "href", buffer, theHref);
                    }
                    {
                        String theId;
                        theId = this.getId();
                        strategy.appendField(locator, this, "id", buffer, theId);
                    }
                    return buffer;
                }

                public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                    if (!(object instanceof CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption)) {
                        return false;
                    }
                    if (this == object) {
                        return true;
                    }
                    final CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption that = ((CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption) object);
                    {
                        String lhsValue;
                        lhsValue = this.getValue();
                        String rhsValue;
                        rhsValue = that.getValue();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue), LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue)) {
                            return false;
                        }
                    }
                    {
                        String lhsName;
                        lhsName = this.getName();
                        String rhsName;
                        rhsName = that.getName();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "name", lhsName), LocatorUtils.property(thatLocator, "name", rhsName), lhsName, rhsName)) {
                            return false;
                        }
                    }
                    {
                        String lhsCreated;
                        lhsCreated = this.getCreated();
                        String rhsCreated;
                        rhsCreated = that.getCreated();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "created", lhsCreated), LocatorUtils.property(thatLocator, "created", rhsCreated), lhsCreated, rhsCreated)) {
                            return false;
                        }
                    }
                    {
                        String lhsLastUpdated;
                        lhsLastUpdated = this.getLastUpdated();
                        String rhsLastUpdated;
                        rhsLastUpdated = that.getLastUpdated();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "lastUpdated", lhsLastUpdated), LocatorUtils.property(thatLocator, "lastUpdated", rhsLastUpdated), lhsLastUpdated, rhsLastUpdated)) {
                            return false;
                        }
                    }
                    {
                        String lhsHref;
                        lhsHref = this.getHref();
                        String rhsHref;
                        rhsHref = that.getHref();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "href", lhsHref), LocatorUtils.property(thatLocator, "href", rhsHref), lhsHref, rhsHref)) {
                            return false;
                        }
                    }
                    {
                        String lhsId;
                        lhsId = this.getId();
                        String rhsId;
                        rhsId = that.getId();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsId), LocatorUtils.property(thatLocator, "id", rhsId), lhsId, rhsId)) {
                            return false;
                        }
                    }
                    return true;
                }

                public boolean equals(Object object) {
                    final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                    return equals(null, null, object, strategy);
                }

                public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                    int currentHashCode = 1;
                    {
                        String theValue;
                        theValue = this.getValue();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue);
                    }
                    {
                        String theName;
                        theName = this.getName();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "name", theName), currentHashCode, theName);
                    }
                    {
                        String theCreated;
                        theCreated = this.getCreated();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "created", theCreated), currentHashCode, theCreated);
                    }
                    {
                        String theLastUpdated;
                        theLastUpdated = this.getLastUpdated();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lastUpdated", theLastUpdated), currentHashCode, theLastUpdated);
                    }
                    {
                        String theHref;
                        theHref = this.getHref();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "href", theHref), currentHashCode, theHref);
                    }
                    {
                        String theId;
                        theId = this.getId();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theId), currentHashCode, theId);
                    }
                    return currentHashCode;
                }

                public int hashCode() {
                    final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                    return this.hashCode(null, strategy);
                }

                public Object clone() {
                    return copyTo(createNewInstance());
                }

                public Object copyTo(Object target) {
                    final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
                    return copyTo(null, target, strategy);
                }

                public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
                    final Object draftCopy = ((target == null)?createNewInstance():target);
                    if (draftCopy instanceof CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption) {
                        final CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption copy = ((CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption) draftCopy);
                        if (this.value!= null) {
                            String sourceValue;
                            sourceValue = this.getValue();
                            String copyValue = ((String) strategy.copy(LocatorUtils.property(locator, "value", sourceValue), sourceValue));
                            copy.setValue(copyValue);
                        } else {
                            copy.value = null;
                        }
                        if (this.name!= null) {
                            String sourceName;
                            sourceName = this.getName();
                            String copyName = ((String) strategy.copy(LocatorUtils.property(locator, "name", sourceName), sourceName));
                            copy.setName(copyName);
                        } else {
                            copy.name = null;
                        }
                        if (this.created!= null) {
                            String sourceCreated;
                            sourceCreated = this.getCreated();
                            String copyCreated = ((String) strategy.copy(LocatorUtils.property(locator, "created", sourceCreated), sourceCreated));
                            copy.setCreated(copyCreated);
                        } else {
                            copy.created = null;
                        }
                        if (this.lastUpdated!= null) {
                            String sourceLastUpdated;
                            sourceLastUpdated = this.getLastUpdated();
                            String copyLastUpdated = ((String) strategy.copy(LocatorUtils.property(locator, "lastUpdated", sourceLastUpdated), sourceLastUpdated));
                            copy.setLastUpdated(copyLastUpdated);
                        } else {
                            copy.lastUpdated = null;
                        }
                        if (this.href!= null) {
                            String sourceHref;
                            sourceHref = this.getHref();
                            String copyHref = ((String) strategy.copy(LocatorUtils.property(locator, "href", sourceHref), sourceHref));
                            copy.setHref(copyHref);
                        } else {
                            copy.href = null;
                        }
                        if (this.id!= null) {
                            String sourceId;
                            sourceId = this.getId();
                            String copyId = ((String) strategy.copy(LocatorUtils.property(locator, "id", sourceId), sourceId));
                            copy.setId(copyId);
                        } else {
                            copy.id = null;
                        }
                    }
                    return draftCopy;
                }

                public Object createNewInstance() {
                    return new CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption();
                }

            }

        }

    }

}
