//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 12:34:44 PM IST 
//


package org.openmrs.module.dhisintegration.api.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openmrs.module.dhisintegration.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openmrs.module.dhisintegration.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportTemplates }
     * 
     */
    public ReportTemplates createReportTemplates() {
        return new ReportTemplates();
    }

    /**
     * Create an instance of {@link ImportSummary }
     * 
     */
    public ImportSummary createImportSummary() {
        return new ImportSummary();
    }

    /**
     * Create an instance of {@link DataValueSet }
     * 
     */
    public DataValueSet createDataValueSet() {
        return new DataValueSet();
    }

    /**
     * Create an instance of {@link OrgUnitType }
     * 
     */
    public OrgUnitType createOrgUnitType() {
        return new OrgUnitType();
    }

    /**
     * Create an instance of {@link OrgUnitType.OrganisationUnit }
     * 
     */
    public OrgUnitType.OrganisationUnit createOrgUnitTypeOrganisationUnit() {
        return new OrgUnitType.OrganisationUnit();
    }

    /**
     * Create an instance of {@link CategoryCombosType }
     * 
     */
    public CategoryCombosType createCategoryCombosType() {
        return new CategoryCombosType();
    }

    /**
     * Create an instance of {@link CategoryCombosType.CategoryOptionCombo }
     * 
     */
    public CategoryCombosType.CategoryOptionCombo createCategoryCombosTypeCategoryOptionCombo() {
        return new CategoryCombosType.CategoryOptionCombo();
    }

    /**
     * Create an instance of {@link CategoryCombosType.CategoryOptionCombo.CategoryOptions }
     * 
     */
    public CategoryCombosType.CategoryOptionCombo.CategoryOptions createCategoryCombosTypeCategoryOptionComboCategoryOptions() {
        return new CategoryCombosType.CategoryOptionCombo.CategoryOptions();
    }

    /**
     * Create an instance of {@link CategoriesType }
     * 
     */
    public CategoriesType createCategoriesType() {
        return new CategoriesType();
    }

    /**
     * Create an instance of {@link CategoriesType.Category }
     * 
     */
    public CategoriesType.Category createCategoriesTypeCategory() {
        return new CategoriesType.Category();
    }

    /**
     * Create an instance of {@link CategoriesType.Category.CategoryOptions }
     * 
     */
    public CategoriesType.Category.CategoryOptions createCategoriesTypeCategoryCategoryOptions() {
        return new CategoriesType.Category.CategoryOptions();
    }

    /**
     * Create an instance of {@link ImportSummary.Conflicts }
     * 
     */
    public ImportSummary.Conflicts createImportSummaryConflicts() {
        return new ImportSummary.Conflicts();
    }

    /**
     * Create an instance of {@link ReportTemplates.ReportTemplate }
     * 
     */
    public ReportTemplates.ReportTemplate createReportTemplatesReportTemplate() {
        return new ReportTemplates.ReportTemplate();
    }

    /**
     * Create an instance of {@link ReportTemplates.ReportTemplate.DataValueTemplates }
     * 
     */
    public ReportTemplates.ReportTemplate.DataValueTemplates createReportTemplatesReportTemplateDataValueTemplates() {
        return new ReportTemplates.ReportTemplate.DataValueTemplates();
    }

    /**
     * Create an instance of {@link ReportTemplates.Disaggregations }
     * 
     */
    public ReportTemplates.Disaggregations createReportTemplatesDisaggregations() {
        return new ReportTemplates.Disaggregations();
    }

    /**
     * Create an instance of {@link ReportTemplates.DataElements }
     * 
     */
    public ReportTemplates.DataElements createReportTemplatesDataElements() {
        return new ReportTemplates.DataElements();
    }

    /**
     * Create an instance of {@link ImportSummary.DataValueCount }
     * 
     */
    public ImportSummary.DataValueCount createImportSummaryDataValueCount() {
        return new ImportSummary.DataValueCount();
    }

    /**
     * Create an instance of {@link DataValueSet.DataValue }
     * 
     */
    public DataValueSet.DataValue createDataValueSetDataValue() {
        return new DataValueSet.DataValue();
    }

    /**
     * Create an instance of {@link MetaData }
     * 
     */
    public MetaData createMetaData() {
        return new MetaData();
    }

    /**
     * Create an instance of {@link OrgUnitType.OrganisationUnit.Parent }
     * 
     */
    public OrgUnitType.OrganisationUnit.Parent createOrgUnitTypeOrganisationUnitParent() {
        return new OrgUnitType.OrganisationUnit.Parent();
    }

    /**
     * Create an instance of {@link CategoryCombosType.CategoryOptionCombo.CategoryCombo }
     * 
     */
    public CategoryCombosType.CategoryOptionCombo.CategoryCombo createCategoryCombosTypeCategoryOptionComboCategoryCombo() {
        return new CategoryCombosType.CategoryOptionCombo.CategoryCombo();
    }

    /**
     * Create an instance of {@link CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption }
     * 
     */
    public CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption createCategoryCombosTypeCategoryOptionComboCategoryOptionsCategoryOption() {
        return new CategoryCombosType.CategoryOptionCombo.CategoryOptions.CategoryOption();
    }

    /**
     * Create an instance of {@link CategoriesType.Category.Concept }
     * 
     */
    public CategoriesType.Category.Concept createCategoriesTypeCategoryConcept() {
        return new CategoriesType.Category.Concept();
    }

    /**
     * Create an instance of {@link CategoriesType.Category.CategoryOptions.CategoryOption }
     * 
     */
    public CategoriesType.Category.CategoryOptions.CategoryOption createCategoriesTypeCategoryCategoryOptionsCategoryOption() {
        return new CategoriesType.Category.CategoryOptions.CategoryOption();
    }

    /**
     * Create an instance of {@link ImportSummary.Conflicts.Conflict }
     * 
     */
    public ImportSummary.Conflicts.Conflict createImportSummaryConflictsConflict() {
        return new ImportSummary.Conflicts.Conflict();
    }

    /**
     * Create an instance of {@link ReportTemplates.ReportTemplate.DataValueTemplates.DataValueTemplate }
     * 
     */
    public ReportTemplates.ReportTemplate.DataValueTemplates.DataValueTemplate createReportTemplatesReportTemplateDataValueTemplatesDataValueTemplate() {
        return new ReportTemplates.ReportTemplate.DataValueTemplates.DataValueTemplate();
    }

    /**
     * Create an instance of {@link ReportTemplates.Disaggregations.Disaggregation }
     * 
     */
    public ReportTemplates.Disaggregations.Disaggregation createReportTemplatesDisaggregationsDisaggregation() {
        return new ReportTemplates.Disaggregations.Disaggregation();
    }

    /**
     * Create an instance of {@link ReportTemplates.DataElements.DataElement }
     * 
     */
    public ReportTemplates.DataElements.DataElement createReportTemplatesDataElementsDataElement() {
        return new ReportTemplates.DataElements.DataElement();
    }

}
