//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 12:34:44 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dhis2.org/schema/dxf/2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openmrs.module.dhisintegration.api.jaxb;
